<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Constructeur {

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected $characters = ['Rick', 'Morty', 'Beth', 'Jerry', 'Summer'];

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected $seualPattern = ['bi', 'homo', 'hetero'];

	/**
	 * 
	 * @var 
	 * @access protected
	 */
	protected $container;


	/**
	 * @access public
	 * @param  $container 
	 */

	public final  function __construct($container) {

	}


	/**
	 * @access public
	 * @param string $name 
	 * @param  $this->container->get($name) 
	 */

	public final  function __get($name, $this->container->get($name)) {

	}


}
?>
