<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Debug {


	/**
	 * @access public
	 * @param array $array 
	 */

	public final  function ft_print($array) {

	}


}
?>