<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Constructeur
 */
require_once('Constructeur.class.php');

class FormChecker extends Constructeur {


	/**
	 * @access public
	 * @param  $request 
	 * @return array
	 */

	public final  function check($request) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @return string
	 */

	public final  function checkLogin($request) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @return string
	 */

	public final  function checkSignup($request) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @return array
	 */

	public final  function checkProfil($request) {

	}


	/**
	 * @access public
	 * @param string $real 
	 * @param string $test 
	 * @param  $ 
	 * @return bool
	 */

	public final  function checkPassword($real, $test) {

	}


}
?>
