<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MailSender {


	/**
	 * @access public
	 * @param str $dest 
	 * @param str $subject 
	 * @param str $message 
	 * @param str $header 
	 * @return str
	 */

	public final  function sendMail($dest, $subject, $message, $header) {

	}


	/**
	 * @access public
	 * @param str $login 
	 * @param str $dest 
	 * @param str $token 
	 */

	public final  function ValidationMail($login, $dest, $token) {

	}


	/**
	 * @access public
	 * @param str $login 
	 * @param str $dest 
	 * @param str $token 
	 */

	public final  function sendReInitMail($login, $dest, $token) {

	}


}
?>