<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Constructeur
 */
require_once('Constructeur.class.php');

class RouteController extends Constructeur {


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function home($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function signup($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function validation($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function reInitPassword($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function login($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function logout($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function profil($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function password($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function setup($request, $response) {

	}


	/**
	 * @access public
	 * @param  $request 
	 * @param  $response 
	 */

	public final  function seed($request, $response) {

	}


}
?>