<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class SetupModel {


	/**
	 * @access public
	 * @param  $ 
	 */

	public final  function init() {

	}


	/**
	 * @access public
	 * @param int $count 
	 */

	public final  function fakeFactory($count = 100) {

	}


}
?>
