<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Constructeur
 */
require_once('Constructeur.class.php');

class UserModel extends Constructeur {


	/**
	 * @access public
	 * @return array
	 */

	public final  function getUsers() {

	}


	/**
	 * @access public
	 * @param str $pseudo 
	 * @return array
	 */

	public final  function getUser($pseudo) {

	}


	/**
	 * @access public
	 * @param array $post 
	 */

	public final  function setUser($post) {

	}


	/**
	 * @access public
	 * @param int $id 
	 * @return array
	 */

	public final  function getUserById($id) {

	}


	/**
	 * @access public
	 * @param str $email 
	 * @return array
	 */

	public final  function getUserByEmail($email) {

	}


	/**
	 * @access public
	 */

	public final  function updateUser() {

	}


	/**
	 * @access public
	 */

	public final  function updatePassUser() {

	}


	/**
	 * @access public
	 */

	public final  function activate() {

	}


	/**
	 * @access public
	 * @param str $pseudo 
	 * @param str $token 
	 */

	public final  function updateToken($pseudo, $token) {

	}


}
?>