<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Validator {

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected $characters = ['Rick', 'Morty', 'Beth', 'jerry', 'Summer'];

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected $sexualPattern = ['bi', 'homo', 'hetero'];


	/**
	 * @access public
	 * @param array $array 
	 * @param array $keys 
	 * @return bool
	 */

	public final  function validate($array, $keys) {

	}


	/**
	 * @access public
	 * @param array $array 
	 * @param array $keys 
	 * @return bool
	 */

	public final  function ft_isset($array, $keys) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function pseudo($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function password($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function password1($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function email($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function gender($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function sexual_orientation($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function birthdate($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function name($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function forname($test) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function biography($test = true) {

	}


	/**
	 * @access public
	 * @param str $test 
	 * @return bool
	 */

	public final  function submit($test) {

	}


}
?>